### ISSUE TITLE
Salt and Nonce wrong byte size

### ISSUE THREAD

**Issue by ooglykraken** [muquit/libsodium-jna#3]
I posted the same question on the original c libsodium library repo <https://github.com/jedisct1/libsodium/issues/634>. But I figured I'd ask here since I'm using this library. I'm on 32-bit win10 running this in IntelliJ. I installed the c library myself since any documentation for windows is non-existant but when I run the TestSodiumLibrary it fails on 13 tests all with the same error relating to incorrect sizes of nonces and salts. Something like "com.muquit.libsodiumjna.exceptions.SodiumLibraryException: salt is 32, it must be 63310704161062944 bytes". So my thinking is I probably didn't setup access to the c library properly, but I don't have any way of being sure. I was hoping maybe someone would have an idea as to why the incorrect byte size is being read from c in the Java project. I.e for cryptoPwhashScrypt it sets long salt_length to sodium().crypto_pwhash_scryptsalsa208sha256_saltbytes().  In c this is 32U, in java its something like 143250559619563552 since the value is never constant per compilation.

**Comment by muquit** [comment]
I don't have access to 32 bit windows, that's why did not notice this problem. I think the problem is because I used long to declare these functions which works fine on 64 bit systems and even works fine on 32 bit Linux. So I think NativeLong should have been used. Can you change the code in SoldiumLibary.java to see if it works for you.  If it does, I will give another look at the code to see what else needs to be changed.
Change the code as follows:

```
NativeLong crypto_pwhash_scryptsalsa208sha256_saltbytes();
```
Then compare like:
```
if (salt.length != salt_length.intValue())
{
}
```


Thanks.

**Comment by muquit** [comment]
I made some changes to develop branch. Please get that to see how the unit tests behave on 32 bit windows.

Thanks

**Comment by ooglykraken** [comment]
Thank you, I'm getting it setup on a 32 and 64 bit windows to compare. I'll get back to you within 24 hours.

**Comment by ooglykraken** [comment]
I apologize for the delay, complications in double checking that it wasn't my fault when compiling the c library prevented me from getting testing done on both machines. As of now I've got it working on the 32 bit machine but when running the testing it fails on testDeriveKeyScript, testDeriveKeyVerify, testEncryptPrivateKey, testPasswordHash, testDeriveKeyArgon2. For all of them the variable 'rc' returns -1 instead of 0. I'll continue working on it and report what I find.

**Comment by muquit** [comment]
To clarify, does it mean that the changes I made to use NativeLong in dev brnach work on 32 bit windows?
Thanks

**Comment by ooglykraken** [comment]
Yes the byte size mismatch is fixed.

**Comment by muquit** [comment]
That's great! If you can make the unit tests work, please send a pull request.  Note: test vectors are generated using libsodium 1.0.15.

Thanks.
